### ISSUE TITLE
Изменить кнопки на страницах сравнения 

### ISSUE THREAD

**Issue by GloomlySeth** [AlexeiZubarik/Decision#11]
При сравнении значений критериев есть кнопка  "CONFIRM".  Если её нажать, то сравнение значений критериев заканчивается и происходит переход на сравнение критериев.  Делаем так, чтобы эта кнопка появлялась только после того, как пользователь проходит все сравнения. 

   Меняем название  кнопки "сохранить" на  "Далее"

**Comment by AlekseySmorshchok** [comment]
Сделано
