### ISSUE TITLE
В новом созданном решении добавляет одинаковые варианты решений

### ISSUE THREAD

**Issue by marisik** [AlexeiZubarik/Decision#35]
![image](https://user-images.githubusercontent.com/40168039/41406967-9ed35170-6fd6-11e8-813d-128f9ac5823e.png)

В критериях та же ситуация

**Comment by AlekseySmorshchok** [comment]
сделано

**Comment by GloomlySeth** [comment]
![default](https://user-images.githubusercontent.com/18662965/41466053-2ef75bd4-70a9-11e8-858a-0d8f37b5bd85.png)

Не уверен. Это страница с добавлением вариантов.
