### ISSUE TITLE
Не отображается таблица для ввода значений критериев

### ISSUE THREAD

**Issue by GloomlySeth** [AlexeiZubarik/Decision#5]
Вижу такое после заполнения критериев и нажатия кнопки "Confirm"

Кто берётся исправлять пишите комент, чтобы вдвоём одно и тоже не делали.

**Comment by SenchenkoDV** [comment]
Я беру.

**Comment by GloomlySeth** [comment]
не торопись. Я, судя по всему, не ту версию смотрел
