### ISSUE TITLE
Страница не на своём месте

### ISSUE THREAD

**Issue by GloomlySeth** [AlexeiZubarik/Decision#9]
Страница с перечнем (шкалой оценок) появляется до ввода значений критериев, а должна быть после

**Comment by GloomlySeth** [comment]
Я подумал. Лучше пусть будет. 

1  Она подготовил пользователя к последующим шагам
2 Не каждый догадается её включить в нужный момент

**Comment by AlekseySmorshchok** [comment]
сделано

**Comment by GloomlySeth** [comment]
Не совсем.

Ты её убрал из несвоего места. Но она должна появиться перед страницей http://93.125.115.115:8080/decision/pairedComparisomComponent
с кнопкой далее.

А при нажатии "Далее"  спрятаться в шторку как сделано на странице http://93.125.115.115:8080/decision/addvaluecriterion

**Comment by AlekseySmorshchok** [comment]
сделано, но не залито)
